name: My First GitHub Action  # Name of the workflow

on: 
  push:  # Runs when you push to the repository
  pull_request:  # Also runs when a pull request is opened

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Specifies the environment to run the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fetches the repository's code

      - name: Print Hello Message
        run: echo "Hello, GitHub Actions!"  # Executes a simple command
